apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: 'https://aws.github.io/eks-charts'
    chart: aws-load-balancer-controller
    targetRevision: 1.8.1
    helm:
      valueFiles:
        - ../../values.yaml
      valuesObject:
        clusterName: {{ .Values.global.clusterName | default "finflow-prod-eks" | quote }}
        region: {{ .Values.aws_region | default "eu-central-1" | quote }}
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: {{ .Values.global.infraRoleArn | quote }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true