apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: 'https://aws.github.io/eks-charts'
    chart: aws-load-balancer-controller
    targetRevision: 1.8.1
    helm:
      valuesObject:
        clusterName: finflow-prod-eks
        region: eu-central-1
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::668751951204:role/finflow-prod-alb-controller-irsa"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true