apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: finflow-rabbitmq
  namespace: argocd

spec:
  project: infrastructure

  source:
    repoURL: https://groundhog2k.github.io/helm-charts/
    chart: rabbitmq
    targetRevision: 2.3.1

    helm:
      valuesObject:
        image:
          registry: "docker.io"
          repository: "rabbitmq"
          tag: "3.13-management"

        authentication:
          existingSecret: finflow-rabbitmq-secret
          user:
            secretKey: rabbitmq-username
          password:
            secretKey: rabbitmq-password
          erlangCookie:
            secretKey: rabbitmq-erlang-cookie

        replicaCount: 1

        storage:
          requestedSize: 8Gi
          className: gp2
          accessModes:
            - ReadWriteOnce

        service:
          type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: finflow-infra

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true