apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finflow-rabbitmq
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 16.0.14
    helm:
      valuesObject:
        auth:
          username: finflow_user
          existingPasswordSecret: finflow-rabbitmq-secret
          existingPasswordSecretKey: rabbitmq-password
        replicaCount: 1
        persistence:
          enabled: true
          storageClass: gp2
          accessModes:
            - ReadWriteOnce
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: finflow-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true