apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finflow-rabbitmq
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 14.x.x
    chart: rabbitmq
    helm:
      valuesObject:
        image:
          registry: "docker.io"
          repository: "rabbitmq"
          tag: "3.13.7"
        auth:
          username: "finflow_user"
          existingPasswordSecret: "finflow-rabbitmq-secret"
          existingPasswordSecretKey: "RABBITMQ_PASSWORD"
        persistence:
          storageClass: "gp2"
        replicaCount: 1
        initContainers: []
        containerSecurityContext:
          readOnlyRootFilesystem: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: finflow-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true