apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finflow-gotenberg
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: {{ .Values.global.repoUrl | quote }}
    targetRevision: {{ .Values.global.repoBranch | default "gitops/auto" | quote }}
    path: k8s/charts/app-component
    helm:
      valueFiles:
        - ../../values.yaml
      valuesObject:
        enabled: true
        global:
          imageTag: "8.x.x"
          registry: "docker.io"
        imageName: "gotenberg/gotenberg"
        replicaCount: 1
        containerPort: 3000
        hasService: true
        hasIngress: false
        serviceAccount:
          name: "finflow-infra-sa"
        csiSecrets:
          enabled: true
          secretProviderClass: "finflow-infra-secrets-provider"
          secretName: "finflow-database-secret"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: finflow-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
