apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finflow-secrets-sync
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: {{ .Values.global.repoUrl | quote }}
    targetRevision: HEAD
    path: k8s/secrets-config
    helm:
      valueFiles:
        - ../values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true