apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: finflow-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Project for FinFlow core application services"
  destinations:
    - namespace: finflow-apps
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
