apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Project for data stores and internal utilities"
  destinations:
    - namespace: finflow-infra
      server: https://kubernetes.default.svc
    - namespace: finflow-apps
      server: https://kubernetes.default.svc
    - namespace: finflow-monitoring
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
