{{- if and .Values.enabled .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.imageName | replace "/" "-" }}-config
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}