{{- if .Values.hasIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.imageName | replace "/" "-" }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.acmCertificateArn | quote }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: finflow-public

spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.imageName | replace "/" "-" }}
                port:
                  number: {{ .Values.containerPort }}
{{- end }}