acmCertificateArn: "arn:aws:acm:eu-central-1:668751951204:certificate/3a72e4d5-aba1-49ff-aa98-12e7d5b02329"
appDomain: "finflow.pp.ua"

global:
  imageTag: "latest"
  registry: "whatislavx"
  repoUrl: "https://github.com/whatislavx/personal-finance-analyzer-infra.git"
  repoBranch: "gitops/auto"
  s3Endpoint: "https://s3.eu-central-1.amazonaws.com"
  s3Bucket: "finflow-prod-results-668751951204"
  s3Region: "eu-central-1"
  appsRoleArn: "arn:aws:iam::668751951204:role/finflow-prod-apps-irsa"
  infraRoleArn: "arn:aws:iam::668751951204:role/finflow-prod-infra-irsa"

api:
  imageTag: "v1.0.0"
  registry: "whatislavx"

worker:
  imageTag: "v1.0.0"
  registry: "whatislavx"

frontend:
  imageTag: "v1.0.0"
  registry: "whatislavx"
