apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: finflow-apps
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: finflow-api
