apiVersion: v1
kind: ServiceAccount
metadata:
  name: finflow-api-sa
  namespace: finflow-apps
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.appsRoleArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: finflow-worker-sa
  namespace: finflow-apps
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.appsRoleArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: finflow-infra-sa
  namespace: finflow-infra
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.infraRoleArn | quote }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: finflow-apps-secrets-provider
  namespace: finflow-apps
spec:
  provider: aws
  secretObjects:
    - secretName: finflow-api-secret
      type: Opaque
      data:
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: JWT_SECRET_KEY
          key: JWT_SECRET_KEY
        - objectName: RABBITMQ_PASSWORD
          key: RABBITMQ_PASSWORD
    - secretName: finflow-worker-secret
      type: Opaque
      data:
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: RABBITMQ_PASSWORD
          key: RABBITMQ_PASSWORD
  parameters:
    objects: |
      - objectName: "finflow-prod-secrets"
        objectType: "secretsmanager"
        jmespath:
          - path: "DB_PASSWORD"
            objectAlias: "DB_PASSWORD"
          - path: "JWT_SECRET_KEY"
            objectAlias: "JWT_SECRET_KEY"
          - path: "RABBITMQ_PASSWORD"
            objectAlias: "RABBITMQ_PASSWORD"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: finflow-infra-secrets-provider
  namespace: finflow-infra
spec:
  provider: aws
  secretObjects:
    - secretName: finflow-database-secret
      type: Opaque
      data:
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
    - secretName: finflow-rabbitmq-secret
      type: Opaque
      data:
        - objectName: RABBITMQ_PASSWORD
          key: RABBITMQ_PASSWORD
  parameters:
    objects: |
      - objectName: "finflow-prod-secrets"
        objectType: "secretsmanager"
        jmespath:
          - path: "DB_PASSWORD"
            objectAlias: "DB_PASSWORD"
          - path: "RABBITMQ_PASSWORD"
            objectAlias: "RABBITMQ_PASSWORD"
